### ISSUE TITLE
[BUG] Handling incorrect API Key

### ISSUE THREAD

**Issue by DarkAlchy** [blib-la/captain#19]
Doesn't tell me what it is doing while the spinning thing is happening for captioning.  Bad.

![image](https://github.com/blib-la/captain/assets/10561690/8433d6dd-f4d3-40e9-a4c4-43cd9dead3a9)

Maybe it is being denied and the program is in lala land not handling a case like that?

----

Version: 1.0.0-beta.4

**Comment by pixelass** [comment]
Thanks for the input.
we're working on it.

**Comment by pixelass** [comment]
@DarkAlchy something like this? (unstyled prototype)

https://github.com/blib-la/captain/assets/1148334/90567c7e-3e2a-46de-b263-2ad8e6dd69e4

**Comment by DarkAlchy** [comment]
That would help, though I think in my case my key was not accepted and the program went into oblivion not expecting that.

**Comment by pixelass** [comment]
ah, hm, yeah I can check if we are missing a catch statement there. Keeping this open since it is useful.

**Comment by pixelass** [comment]
![image](https://github.com/blib-la/captain/assets/1148334/c7ddf50e-5607-49a3-8774-ca154ff1eb94)

This will be part of the next release. Not perfect, but better than the current behavior

**Comment by DarkAlchy** [comment]
Looks better, yes.
