### ISSUE TITLE
Info about hotkeys

### ISSUE THREAD

**Issue by pixelass** [blib-la/captain#2]
As a user,
I want to be informed about hotkeys,
So that I know my options.

I expect to see an info icon or similar which shows the available hotkeys as legend

**Comment by MNeMoNiCuZ** [comment]
Ideally in some kind of "Settings" menu, even if they are not configurable yet. It's probably a good idea to prep for it.

**Comment by pixelass** [comment]
prepared for next release

@MNeMoNiCuZ we also have this simple menu now:

currently includes light/dark mode toggle if users don't want to rely on OS-settings

![image](https://github.com/blib-la/captain/assets/1148334/3550d75f-5426-482e-87b8-fa26b5fe93a7)

![image](https://github.com/blib-la/captain/assets/1148334/ae5d2285-b718-4962-8d45-f92397a5a647)
