### ISSUE TITLE
live-painting: Still active / ping

### ISSUE THREAD

**Issue by TimPietrusky** [blib-la/captain#59]
**Is your feature request related to a problem? Please describe.** A clear and concise description
The live-painting process should provide some kind of API, so that we can see if the process is still running. This comes in handy, when we go from the live-painting screen to somewhere else and back to live-painting.

**Comment by pixelass** [comment]
This issue has mostly been solved in the current alpha branch. The process is closed when the window/view is closed, therefore no lifesign is required
