### ISSUE TITLE
Skip installer when nothing has changed

### ISSUE THREAD

**Issue by TimPietrusky** [blib-la/captain#61]
**Is your feature request related to a problem? Please describe.** 
When starting the app, the installer process is always shown when there was an update to the app version. 

**Describe the solution you'd like**
The installer should only ever be shown when the app gets installed, not when there is a version update of the app. I don't want to change my language / theming settings. I might only need to download the python-emebedded if that changed.

**Comment by pixelass** [comment]
this has been added in #230
