### ISSUE TITLE
[BUG]: The downloaded models are in the wrong subpath

### ISSUE THREAD

**Issue by TimPietrusky** [blib-la/captain#95]
**Describe the bug** 
When a model is downloaded as archive and then unpacked, the subpath contains the folder that was used when the model was actually packed. This leads to subpaths like this: `\Captain_Data\downloads\stable-diffusion\checkpoints\stabilityai\sd-turbo\fp16\sd-turbo-fp16`

**Expected behavior**
The model itself should be in the subpath as defined by Captain, not containing the folder that was used when it was packed: `\Captain_Data\downloads\stable-diffusion\checkpoints\stabilityai\sd-turbo\fp16`

**Versions:**

- OS: Windows 11
- Captain: 1.0.0-alpha.23

**Comment by pixelass** [comment]
this has been fixed by #210
